name: Cdk deploy

on:
  push:
    branches: [staging, production]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "(github.ref_name == 'staging' && !contains(github.event.head_commit.message, 'skip ci')) || github.ref_name == 'production'"
    environment: ${{github.ref_name}}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm 8
        run: npm i -g npm@8 --registry=https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          dry_run: false
          branches: "production"
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git

      - name: Merge production to staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "Deploy: Merge production to staging"
          from_branch: production
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge staging to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "Deploy: Merge staging to main"
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
