name: Cdk deploy

on:
  push:
    branches: [staging, production]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    environment: ${{github.ref_name}}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm 8
        run: npm i -g npm@8 --registry=https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
